
<NavButton@Button>:
    on_release: app.root.screen_man.current = self.text
    font_size: 20

<NavBarTop>:
    orientation: 'horizontal'
    size_hint_y: None
    height: "20dp"
    NavButton:
        text: 'Main'
    NavButton:
        text: 'Clock'
    NavButton:
        text: 'Status'

<NavBarBot>:
    orientation: 'horizontal'
    size_hint_y: None
    height: "20dp"
    NavButton:
        text: 'Weather'
    NavButton:
        text: 'Clock'
    NavButton:
        text: 'Status'
